In [1]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [5]:
print(data)
print(data.shape)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]
(10, 5)


In [14]:
#find the mean for each feature 
print((np.mean(data, axis = 0)).shape)
mean_1D = np.mean(data, axis = 0)
#find the std of each feature
print(np.std(data, axis=0))
std_1D = np.std(data, axis=0)
#substract the mean
print(data-mean_1D)
#devide the whole by std
print((data-mean_1D)/std_1D)


(5,)
[0.18880201 0.31226926 0.29810476 0.28105224 0.24648668]
[[ 0.20344878 -0.41972612  0.09397858  0.22671326  0.05947394]
 [-0.34307522 -0.24241521  0.22086106 -0.35297979 -0.35069326]
 [ 0.11748795  0.51291527 -0.53572138 -0.00989836  0.37358789]
 [ 0.0446542   0.28127725 -0.24779358  0.3956835   0.27554271]
 [-0.0253275  -0.29830802 -0.16632889  0.15204299  0.0028001 ]
 [-0.13385787  0.17728891 -0.02653141  0.12830656  0.16200588]
 [ 0.23735133  0.08116908  0.36897923 -0.20285454 -0.34857372]
 [-0.26717181 -0.32649371  0.28901168 -0.47519431  0.18725407]
 [-0.02028571  0.37880892 -0.34072211  0.33475968 -0.08738043]
 [ 0.18677583 -0.14451637  0.34426683 -0.19657899 -0.27401718]]
[[ 1.0775774  -1.34411605  0.31525355  0.80665878  0.24128662]
 [-1.81711634 -0.77630186  0.74088404 -1.25592235 -1.42276759]
 [ 0.62228127  1.64254169 -1.797091   -0.03521894  1.51565143]
 [ 0.23651339  0.90075228 -0.83122987  1.40786459  1.11788073]
 [-0.13414844 -0.95529104 -0.55795449  0.54097769  0.01

In [16]:
def standardize(x):
    """Standardize the input data x

    Args:
        x: numpy array of shape=(num_samples, num_features)

    Returns:
        standardized data, shape=(num_samples, num_features)

    >>> standardize(np.array([[1, 2], [3, 4], [5, 6]]))
    array([[-1.22474487, -1.22474487],
           [ 0.        ,  0.        ],
           [ 1.22474487,  1.22474487]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: standardize input data x
    std_data = (x - np.mean(x, axis=0))/np.std(x, axis=0)
    # ***************************************************
    # raise NotImplementedError
    return std_data


test(standardize)

✅ Your `standardize` passed 1 tests.


In [17]:
std_data = standardize(data)
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 1.0775774  -1.34411605  0.31525355  0.80665878  0.24128662]
 [-1.81711634 -0.77630186  0.74088404 -1.25592235 -1.42276759]
 [ 0.62228127  1.64254169 -1.797091   -0.03521894  1.51565143]
 [ 0.23651339  0.90075228 -0.83122987  1.40786459  1.11788073]
 [-0.13414844 -0.95529104 -0.55795449  0.54097769  0.01136005]
 [-0.70898541  0.56774371 -0.08900028  0.45652209  0.65726018]
 [ 1.2571441   0.25993298  1.23775021 -0.72176808 -1.4141686 ]
 [-1.41508984 -1.04555188  0.96949701 -1.69076861  0.75969247]
 [-0.10744434  1.21308427 -1.14296098  1.19109415 -0.35450368]
 [ 0.98926822 -0.46279408  1.15485183 -0.69943932 -1.11169162]] 

 [-1.66533454e-16  4.99600361e-17 -2.22044605e-17  1.11022302e-17
  3.33066907e-16] 

 [1. 1. 1. 1. 1.]
